/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v1_jobs_get"];
        put?: never;
        /** Create Job */
        post: operations["create_job_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Job */
        post: operations["upload_job_api_v1_jobs_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Delete Job */
        delete: operations["delete_job_api_v1_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audio */
        get: operations["get_audio_api_v1_jobs__job_id__audio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/bundle.zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Bundle */
        get: operations["get_bundle_api_v1_jobs__job_id__bundle_zip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/clips/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Clip */
        get: operations["get_clip_api_v1_jobs__job_id__clips__index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/resegment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resegment */
        post: operations["resegment_api_v1_jobs__job_id__resegment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Result */
        get: operations["get_result_api_v1_jobs__job_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/subtitles.{fmt}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Subtitles */
        get: operations["get_subtitles_api_v1_jobs__job_id__subtitles__fmt__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_job_api_v1_jobs_upload_post */
        Body_upload_job_api_v1_jobs_upload_post: {
            /** Asrbackend */
            asrBackend?: string | null;
            /** File */
            file: string;
            /** Hardpause */
            hardPause?: number | null;
            /** Language */
            language?: string | null;
            /** Leadpad */
            leadPad?: number | null;
            /** Makeclips */
            makeClips?: boolean | null;
            /** Maxduration */
            maxDuration?: number | null;
            /** Minduration */
            minDuration?: number | null;
            /** Subtitlesource */
            subtitleSource?: string | null;
            /** Tailpad */
            tailPad?: number | null;
        };
        /** ConfigDefaultsResponse */
        ConfigDefaultsResponse: {
            /** Asrbackend */
            asrBackend: string;
            /** Asrmodel */
            asrModel: string;
            /** Hardpause */
            hardPause: number;
            /** Language */
            language: string | null;
            /** Leadpad */
            leadPad: number;
            /** Maxduration */
            maxDuration: number;
            /** Minduration */
            minDuration: number;
            /**
             * Subtitlesource
             * @enum {string}
             */
            subtitleSource: "auto" | "existing" | "asr";
            /** Tailpad */
            tailPad: number;
        };
        /** ConfigResponse */
        ConfigResponse: {
            /** Allowlocalpaths */
            allowLocalPaths: boolean;
            /** Asrbackends */
            asrBackends: string[];
            defaults: components["schemas"]["ConfigDefaultsResponse"];
        };
        /** CreateJobRequest */
        CreateJobRequest: {
            /** Asrbackend */
            asrBackend?: string | null;
            /**
             * Hardpause
             * @default 0.75
             */
            hardPause?: number;
            /**
             * Language
             * @default en
             */
            language?: string | null;
            /**
             * Leadpad
             * @default 0.3
             */
            leadPad?: number;
            /**
             * Makeclips
             * @default false
             */
            makeClips?: boolean;
            /**
             * Maxduration
             * @default 30
             */
            maxDuration?: number;
            /**
             * Minduration
             * @default 1
             */
            minDuration?: number;
            /** Source */
            source: string;
            /**
             * Subtitlesource
             * @default auto
             * @enum {string}
             */
            subtitleSource?: "auto" | "existing" | "asr";
            /**
             * Tailpad
             * @default 0.4
             */
            tailPad?: number;
        };
        /** ErrorResponse */
        ErrorResponse: {
            /** Code */
            code: string;
            /** Detail */
            detail: string;
        };
        /** JobPageResponse */
        JobPageResponse: {
            /** Items */
            items: components["schemas"]["JobResponse"][];
            /** Nextcursor */
            nextCursor: string | null;
        };
        /** JobResponse */
        JobResponse: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            error: components["schemas"]["ErrorResponse"] | null;
            /** Id */
            id: string;
            /** Message */
            message: string;
            /** Progress */
            progress: number;
            /** Sentencecount */
            sentenceCount: number;
            /** Source */
            source: string;
            /** Stage */
            stage: ("downloading" | "preparingAudio" | "transcribing" | "segmenting") | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed";
            /** Title */
            title: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** JobResultResponse */
        JobResultResponse: {
            /** Audiourl */
            audioUrl: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Duration */
            duration: number;
            /** Hasclips */
            hasClips: boolean;
            /** Jobid */
            jobId: string;
            /** Language */
            language: string | null;
            /** Sentencecount */
            sentenceCount: number;
            /** Sentences */
            sentences: components["schemas"]["SentenceResponse"][];
            /** Sourceurl */
            sourceUrl: string | null;
            /** Thumbnailurl */
            thumbnailUrl: string | null;
            /** Title */
            title: string;
            /** Transcriptsource */
            transcriptSource: string;
            /** Uploader */
            uploader: string | null;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed";
        /** ProblemDetails */
        ProblemDetails: {
            /** Code */
            code: string;
            /** Detail */
            detail: string;
            /** Requestid */
            requestId: string;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /** Type */
            type: string;
        };
        /** ResegmentRequest */
        ResegmentRequest: {
            /** Hardpause */
            hardPause?: number | null;
            /** Leadpad */
            leadPad?: number | null;
            /** Maxduration */
            maxDuration?: number | null;
            /** Minduration */
            minDuration?: number | null;
            /** Tailpad */
            tailPad?: number | null;
        };
        /** SentenceResponse */
        SentenceResponse: {
            /** Duration */
            duration: number;
            /** End */
            end: number;
            /** Index */
            index: number;
            /** Speechend */
            speechEnd: number;
            /** Speechstart */
            speechStart: number;
            /** Start */
            start: number;
            /** Text */
            text: string;
            /** Words */
            words: components["schemas"]["WordResponse"][];
        };
        /** WordResponse */
        WordResponse: {
            /** End */
            end: number;
            /** Probability */
            probability: number | null;
            /** Start */
            start: number;
            /** Text */
            text: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_config_api_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description Problem Details */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Problem Details */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    list_jobs_api_v1_jobs_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["JobStatus"] | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPageResponse"];
                };
            };
            /** @description Problem Details */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Problem Details */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    create_job_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Problem Details */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Problem Details */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    upload_job_api_v1_jobs_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_job_api_v1_jobs_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Problem Details */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Problem Details */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Problem Details */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Problem Details */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    delete_job_api_v1_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem Details */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Problem Details */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    get_audio_api_v1_jobs__job_id__audio_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem Details */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Problem Details */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    get_bundle_api_v1_jobs__job_id__bundle_zip_get: {
        parameters: {
            query?: {
                clips?: boolean;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem Details */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Problem Details */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    get_clip_api_v1_jobs__job_id__clips__index__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem Details */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Problem Details */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    resegment_api_v1_jobs__job_id__resegment_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResegmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResultResponse"];
                };
            };
            /** @description Problem Details */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Problem Details */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    get_result_api_v1_jobs__job_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResultResponse"];
                };
            };
            /** @description Problem Details */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Problem Details */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    get_subtitles_api_v1_jobs__job_id__subtitles__fmt__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                fmt: "srt" | "vtt" | "txt";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Problem Details */
            "4XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Problem Details */
            "5XX": {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
