from collections.abc import Callable
from pathlib import Path
from typing import Protocol

from looplish_api.domain.models import (
    Job,
    JobPage,
    JobQuery,
    JobResult,
    MediaInfo,
    Transcript,
)

ProgressCallback = Callable[[float, str], None]


class TranscriptionBackend(Protocol):
    name: str

    def transcribe(
        self,
        audio_path: Path,
        language: str | None,
        progress: ProgressCallback | None,
    ) -> Transcript: ...


class MediaDownloader(Protocol):
    def download(
        self,
        url: str,
        workdir: Path,
        subtitle_languages: tuple[str, ...],
    ) -> MediaInfo: ...


class MediaProcessor(Protocol):
    def probe_duration(self, source: Path) -> float: ...
    def to_web_audio(self, source: Path, target: Path) -> Path: ...
    def to_asr_wav(self, source: Path, target: Path) -> Path: ...
    def to_asr_mp3(self, source: Path, target: Path) -> Path: ...
    def slice_asr_mp3(self, source: Path, target: Path, start: float, duration: float) -> Path: ...
    def slice_audio(self, source: Path, target: Path, start: float, duration: float) -> Path: ...


class JobRepository(Protocol):
    def save(self, job: Job) -> None: ...
    def get(self, job_id: str) -> Job | None: ...
    def list(self, query: JobQuery) -> JobPage: ...
    def delete(self, job_id: str) -> bool: ...
    def recover_interrupted(self) -> int: ...


class ArtifactStore(Protocol):
    def job_dir(self, job_id: str) -> Path: ...
    def source_dir(self, job_id: str) -> Path: ...
    def clips_dir(self, job_id: str) -> Path: ...
    def artifact_path(self, job_id: str, name: str) -> Path: ...
    def write_result(self, job_id: str, result: JobResult) -> None: ...
    def read_result(self, job_id: str) -> JobResult | None: ...
    def delete_job_dir(self, job_id: str) -> None: ...
